travis:
  secure:
    BINSTAR_TOKEN: ZBSqQekcGQWK1ls6tshMEipNsXuXVEdZR/sIyYVA5InKqXitEbzTSvmvyaCDnw4NbiDnf5p00eIjLxhT8p98cEXB/eIfd20GPMzL3nC+P9GrzJoIzJj8lGy/cyfKCiNWnpomrSLfYyBrG3Tuq7M6BWgMiZWrJbOh/DjW/yc1qG5ldS90nJRyl/vXuBuf6dT4R7Z7SnEYNH/JVB18CtTDED9AfTIzJKYJtyJL+ijspL9lbb+8squWgnBbHqhkR9cSWMLq6WvuU8/CTfnSrCdgrdhjIUen6kp4uDfvS9bWQpgA3ta9NzXKtGfd2Lv5Rof4h27OE6C+FEK5UEky+aL4kREqWhEEQca32UIyPqFZh0qWr7uxLis2jl1ZKrbe70LvFNaNmvEMHPfeopoWTsFR12NI166638hFCsJBu6Fc3imFCG0CaMSRC0+3wAvra+rlFX8xqtGuPtOLt2/eBTLFNMDInA6fo+HZZnTJDsfwS3VMugOrwzumyzgv4PWAcZju5mCG/7NgxGOyI3z8BQxFvt7wvNEW5ufH59NjSAbmfMe1nHAsYUVCsFRra8uc5wwI3HKFgkIPAV+LwyaJjNqSwx4PeyNRKuzsork72hPJ2iTy0LY+3ntvzk0s97eNuRzmXFrYFvyiGGTKPQlrY2lye+2KSpjjKpTZBCTlAPb7Gsw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
